USE ETRADE

SELECT ID, CUSTOMERNAME

FROM Customers

INSERT INTO Customers
(CUSTOMERNAME, CITY, BIRTHDATE, DISTRICT, GENDER)
VALUES
('Elon Musk', 'South Africa', '19600811', 'Some city', 'E')

SELECT *
FROM Customers

INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Volkan ÇEKÝP','Bartýn','Kurucaþile','1997-10-24 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Serhat GÜNDOÐAN','Rize','Pazar / Rize','1966-02-03 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Irmak TAHSÝNOÐLU','Erzincan','Çayýrlý','1940-06-23 00:00:00.000','K')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Yaþar SAVURGAN','Isparta','Gelendost','1991-08-07 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Remzi ELYÝÐÝT','Giresun','Çanakçý','1953-09-14 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Mehmet Akif POLAST','Bitlis','Mutki','1992-12-25 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Salih FAYDALI','Ordu','Çatalpýnar','1996-08-03 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Münevver AYAOKU','Artvin','Artvin Merkez','1954-04-25 00:00:00.000','K')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Muhammet KUZUCUOÐLU','Aydýn','Germencik','1989-07-10 00:00:00.000','E')
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Nazlýcan ÖZSÝMÝTÇÝ','Þanlýurfa','Viranþehir','1951-12-29 00:00:00.000','K')

SELECT * FROM Customers

UPDATE Customers 
SET NATION = 'TR', AGE = 40

SELECT DATEDIFF(YEAR, '2000-12-06', GETDATE())

UPDATE Customers 
SET NATION = 'TR', AGE = DATEDIFF(YEAR, BIRTHDATE, GETDATE())


DELETE FROM Customers

TRUNCATE TABLE Customers

SELECT	* FROM Customers WHERE AGE=32

SELECT	* FROM Customers WHERE CITY<>'iSTANBUL'

SELECT	* FROM Customers WHERE BIRTHDATE>='19900101'

SELECT	* FROM Customers WHERE BIRTHDATE BETWEEN '19900101' AND '19950101'

SELECT * FROM Customers WHERE AGE BETWEEN 19 AND 32

SELECT * FROM Customers WHERE CUSTOMERNAME LIKE 'ALÝ%'

SELECT * FROM Customers WHERE CUSTOMERNAME LIKE '%ALP'

SELECT * FROM Customers WHERE CUSTOMERNAME LIKE '%AL%'

SELECT * FROM Customers WHERE CUSTOMERNAME NOT LIKE 'ALÝ%'

SELECT * FROM Customers WHERE CITY IN ('iSTANBUL')

UPDATE Customers SET GENDER = 'KADIN' WHERE GENDER = 'K'
UPDATE Customers SET GENDER = 'ERKEK' WHERE GENDER = 'E'

SELECT * FROM CUSTOMERS WHERE GENDER = 'ERKEK' AND CITY = 'ÝSTANBUL'

SELECT * FROM Customers WHERE CITY = 'ÝSTANBUL' OR CITY = 'MERSÝN'

SELECT DISTINCT CITY FROM Customers

SELECT * FROM Customers
ORDER BY ID DESC

SELECT * FROM Customers ORDER BY CITY

SELECT * FROM Customers ORDER BY CITY ASC, DISTRICT ASC, CUSTOMERNAME DESC

SELECT * FROM Customers ORDER BY 2 

SELECT TOP 10 * FROM Customers ORDER BY CUSTOMERNAME

SELECT TOP 1 PERCENT * FROM Customers ORDER BY AGE
