

SELECT 

--CONVERT(DATE, O.DATE_),
DATEPART(MONTH, O.DATE_) AY,
SUM(OD.LINETOTAL) AS TOPLAM_SIPARIS_TUTAR,
SUM(OD.AMOUNT) AS TOPLAM_SIPARIS_MIKTAR,
COUNT(OD.ID) AS TOPLAM_SIPARIS_SAYISI

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID= A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID= O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

--GROUP BY CONVERT(DATE, O.DATE_)
--ORDER BY CONVERT(DATE, O.DATE_)

GROUP BY DATEPART(MONTH, O.DATE_) 
ORDER BY DATEPART(MONTH, O.DATE_) 